"""set total_duration to optional

Revision ID: 13d8aa9c2a61
Revises: 5d8e01bfecb5
Create Date: 2025-08-30 14:14:20.644825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d8aa9c2a61'
down_revision: Union[str, Sequence[str], None] = '5d8e01bfecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
