"""set pseudonym to unique

Revision ID: 2a847310492f
Revises: b6cd72596388
Create Date: 2025-08-25 17:47:41.439582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a847310492f'
down_revision: Union[str, Sequence[str], None] = 'b6cd72596388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'performers', ['pseudonym'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performers', type_='unique')
    # ### end Alembic commands ###
