"""created 3 tables

Revision ID: 4ec14ae0c78f
Revises: 
Create Date: 2025-08-22 11:12:56.841571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec14ae0c78f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonym', sa.String(length=64), nullable=False),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.Column('performance_type', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.String(length=24), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    op.drop_table('performers')
    # ### end Alembic commands ###
