"""changed some poles in user from str to bool

Revision ID: 5d8e01bfecb5
Revises: 1d0a0ea26b3f
Create Date: 2025-08-29 15:35:04.926762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8e01bfecb5'
down_revision: Union[str, Sequence[str], None] = '1d0a0ea26b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
