"""deleted nullable from performer_id

Revision ID: e8a699cc9bd6
Revises: 05de6a593132
Create Date: 2025-08-27 14:30:36.856504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a699cc9bd6'
down_revision: Union[str, Sequence[str], None] = '05de6a593132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('albums', 'performer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
